scrap/urls.py
from django.urls import path
from .views import *

urlpatterns = [
    path('', Index.as_view(),name='index'),
    path('add/', AddAutomation.as_view(),name='add'),
    path('show', ShowAutomations.as_view(),name='show'),
    path('linked/', Linked.as_view(),name='linked'),
    path('user', User.as_view(),name='user'),
    path('status', Changestatus.as_view(),name='status'),
    path('thread', StartThread.as_view(),name='thread'),
    path('stop', StopThread.as_view(),name='stop'),
    path('alldata', AllData.as_view(),name='alldata'),
    path('reject', Reject.as_view(),name='reject'),
    path('database', Database.as_view(),name='database'),
    path('delete-automation', DeleteAutomation.as_view(),name='delete_automation'),
    path('delete-user', DeleteUser.as_view(),name='delete_user'),
    path('edit-automation/<id>', EditAutomation.as_view(),name='edit_automation'),
    path('edit-user/<id>', EditUser.as_view(),name='edit_user'),
    path('add-cron', AddCron.as_view(),name='addcron'),
    path('pause', PauseSchduale.as_view(),name='pause'),
    path('changestatus', ChangeAllStatus.as_view(),name='changestatus'),
    path('actions', Actions.as_view(),name='actions'),
    
   


]

scrapying/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('scrap.urls'))
]

scrap/models.py
from django.db import models



DAYS = (
    ('SUN', 'Sunday'),
    ('MON', 'Monday'),
    ('TUE', 'Tuesday'),
    ('WED', 'Wednessday'),
    ('THU', 'Thursday'),
    ('FRI', 'Friday'),
    ('SAT', 'Saterday')
)

RATE = (
    ('W', 'Weekly'),
    # ('B', 'Biweekly'),
    ('M', 'Monthly'),
)
DATASTATUS = (
    ('P', 'Pending'),
    ('A', 'Approve'),
    ('R', 'Reject'),
)

class LinkedIn(models.Model):
    email = models.EmailField(max_length=255, blank=False, null=True)
    password = models.CharField(max_length=100,  blank=True, null=True)
    
    def __str__(self):
        return self.email

class Geography(models.Model):
    title = models.CharField(max_length=255, blank=False, null=True, verbose_name='Title')
    slug = models.SlugField(max_length=100, unique=True, db_index=True, blank=True, null=True)

    def __str__(self):
        return self.title

class SeniorityLevel(models.Model):
    title = models.CharField(max_length=255, blank=False, null=True, verbose_name='Title')
    slug = models.SlugField(max_length=100, unique=True, db_index=True, blank=True, null=True)
    
    def __str__(self):
        return self.title

class YearAtCompany(models.Model):
    title = models.CharField(max_length=255, blank=False, null=True, verbose_name='Title')
    slug = models.SlugField(max_length=100, unique=True, db_index=True, blank=True, null=True)
    
    def __str__(self):
        return self.title

class YearofExperience(models.Model):
    title = models.CharField(max_length=255, blank=False, null=True, verbose_name='Title')
    slug = models.SlugField(max_length=100, unique=True, db_index=True, blank=True, null=True)
    
    def __str__(self):
        return self.title


class FunctionAtComapny(models.Model):
    title = models.CharField(max_length=255, blank=False, null=True, verbose_name='Title')
    slug = models.SlugField(max_length=100, unique=True, db_index=True, blank=True, null=True)
    
    def __str__(self):
        return self.title


class Automations(models.Model):
    user=models.ForeignKey(LinkedIn, blank=True, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=255, blank=False, null=True, verbose_name='Name')
    geography = models.ForeignKey(Geography, blank=True, null=True, on_delete=models.DO_NOTHING)
    geography_status = models.BooleanField(default=True)
    srlevel = models.ForeignKey(SeniorityLevel, blank=True, null=True, on_delete=models.DO_NOTHING)
    srlevel_status = models.BooleanField(default=True)
    period = models.ForeignKey(YearAtCompany, blank=True, null=True, on_delete=models.DO_NOTHING)
    period_status = models.BooleanField(default=True)
    functionsatcompany = models.ForeignKey(FunctionAtComapny, blank=True, null=True, on_delete=models.DO_NOTHING)
    functionsatcompanyl_status = models.BooleanField(default=True)
    yearsofexperience = models.ForeignKey(YearofExperience, blank=True, null=True, on_delete=models.DO_NOTHING)
    yearsofexperience_status = models.BooleanField(default=True)
    day = models.CharField(max_length=3, choices=DAYS, default="SUN", verbose_name='Day')
    rate = models.CharField(max_length=1, choices=RATE, default="W", verbose_name='Rate')
    status = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.name
class ScriptInterval(models.Model):
    automation=models.ForeignKey(Automations, blank=True, null=True, on_delete=models.CASCADE)
    interval = models.DateTimeField(auto_now=True, null=True,blank=True)
    running = models.BooleanField(default=False, blank=True, null=True)

    def __str__(self):
        return self.automation.name

class AutomationData(models.Model):
    companyname = models.CharField(max_length=200,blank=True,null=True)
    name = models.CharField(max_length=100,blank=True,null=True)
    senioritylevel = models.CharField(max_length=100,blank=True,null=True)
    function = models.CharField(max_length=200,blank=True,null=True)
    degree = models.CharField(max_length=200,blank=True,null=True)
    gradyearstart = models.CharField(max_length=200,blank=True,null=True)
    gradyearend = models.CharField(max_length=200,blank=True,null=True)
    url = models.CharField(max_length=255,blank=True,null=True)
    dateofentry = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    user=models.ForeignKey(LinkedIn, blank=True, null=True, on_delete=models.CASCADE)
    automation = models.ForeignKey(Automations,on_delete=models.CASCADE,blank=True,null=True)
    isduplicated = models.BooleanField(default=False, blank=True, null=True)
    status = models.CharField(max_length=1, choices=DATASTATUS, default="P",  blank=True, null=True, verbose_name='Status')

    def __str__(self):
        return self.name

class Cron(models.Model):
    automation=models.ForeignKey(Automations, blank=True, null=True, on_delete=models.CASCADE)
    execution_type= models.CharField(max_length=200,default='cron')
    is_active=models.BooleanField(blank=True, null=True)
    last_exe_date = models.DateField(max_length=200, null=True, blank=True)
    execution_rate= models.CharField(max_length=200, null=True,blank=True)
    def __str__(self):
        return self.execution_type

scrap/forms.py
from django import forms
from . import models



class DayFrequencyForm(forms.Form):
   days_choices = forms.ChoiceField(choices=models.DAYS)

class RateFrequencyForm(forms.Form):
   rate_choices = forms.ChoiceField(choices=models.RATE)

scrap/views.py
from django.views.generic import TemplateView, View
from .models import *
from .forms import DayFrequencyForm, RateFrequencyForm
from django.urls import reverse
from django.contrib import messages
from django.shortcuts import render, HttpResponseRedirect, redirect
from django.http import HttpResponse
import json
from .forms import *
from django.contrib import messages
import threading
from selenium import webdriver
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import time
from selenium.common.exceptions import NoSuchElementException,StaleElementReferenceException
import random
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
import sqlite3
from sqlite3 import Error
from django.template.loader import render_to_string
from .LinkedInScript import mainScript
from django.conf import settings
from django.core.mail import send_mail
from django.utils import timezone
from datetime import datetime
import time
class Index(TemplateView):
	template_name = 'index.html'
	def get(self,request):
		automations = Automations.objects.all()
		return render(request,self.template_name, locals())


class StartThread(View):
	scrap_id=''
	def get(self,request):
		linkedin_user=request.GET.get("linkedin_user")
		scrap_id = request.GET.get("id")
		automations = Automations.objects.all()
		now=timezone.now()
		try:
			running_script = ScriptInterval.objects.filter(running=True)
			if running_script:
				response_data = {
					"status":False,
					"message":"Scraping on automation "+running_script[0].automation.name+" is already running. Wait until this finished."

				}
				return HttpResponse(json.dumps(response_data), content_type="application/json") 
			get_interval,uja=ScriptInterval.objects.get_or_create(automation_id=int(scrap_id))
	
			fmt = '%Y-%m-%d %H:%M:%S'
			d1 = datetime.strptime(str(get_interval.interval).split('.')[0], fmt)
			d2 = datetime.strptime(str(now).split('.')[0], fmt)
			minutes_diff = (d2 - d1).total_seconds() / 60.0
			testing = True
			if minutes_diff >= 60:
				new_thread = threading.Thread(name='mythread', target=self.startScrap, args=(int(scrap_id),))
				new_thread.daemon = True
				new_thread.start()
				get_interval.interval=now
				get_interval.running=True
				get_interval.save()
				response_data = {
						"status":True,
						"message":"Scrapping is started."

					} 
			else:
				print("Will be after"+str(120-minutes_diff))
				after=round(60-minutes_diff, 2)
				subject = "Script Alert"
				sccuess_status=" New execution request is placed for scraping script. But script it executed recentaly. So wait for "+str(int(after))+" minutes to make new execution request. "
				recipients = ['mario@sdg360.com','rajindermohan001@gmail.com',"director@avioxtechnologies.com"]
				# send_status = mailSend(subject, recipients, html_message=sccuess_status)
				response_data = {
						"status":False,
						"message":sccuess_status

					} 
			return HttpResponse(json.dumps(response_data), content_type="application/json")
		except Exception as e:
			raise e
			return render(request,'index.html')

	def startScrap(self,automationid=0):
		try:
			if automationid !=0:
				status=mainScript(automationid)

				if status['status'] == False:
					print("Not Authenticate")
					error_status=status['msg']	
					recipients = ['mario@sdg360.com','rajindermohan001@gmail.com',"director@avioxtechnologies.com"]
					subject = "Script Status"
					# send_status = mailSend(subject, recipients, html_message=error_status)
					
				if status['status'] == True:
					sccuess_status="Linked in scraping script is completed successfully for instant run."	
					recipients = ['mario@sdg360.com','rajindermohan001@gmail.com',"director@avioxtechnologies.com"]
					# send_status = mailSend(subject, recipients, html_message=sccuess_status)
				ScriptInterval.objects.filter(automation__id=automationid).update(running=False)
		except Exception as e:
			ScriptInterval.objects.filter(automation__id=automationid).update(running=False)
			raise e

def mailSend(subject, recipient_list, message="", html_message=""):
	try:
		email_from = settings.EMAIL_HOST_USER
		send_mail( subject, message, email_from, recipient_list, html_message=html_message )
		return True
	except Exception as e:
		print(str(e))
		return False

 
class StopThread(View):
	def get(self,request):
		try:
			automations = Automations.objects.all()
			scrap_id = request.GET.get("id")
			for th in threading.enumerate():
				thread_name = th.getName()
				if thread_name is "mythread":
					# th.stop()
					th.daemon = False
				print("Stoped..")
		except Exception as e:
			print(e)
		return render(request,'index.html')


class AddAutomation(TemplateView):
	template_name='add_automation.html'
	def get(self,request):
		try:
			day_form = DayFrequencyForm
			rate_form = RateFrequencyForm
			locations = Geography.objects.all()
			srlevel = SeniorityLevel.objects.all()
			period = YearAtCompany.objects.all()
			functionatcom = FunctionAtComapny.objects.all()
			year_of_experience=YearofExperience.objects.all()
			user = LinkedIn.objects.all()

		except Exception as e:
			raise e
	
		return render(request,self.template_name, locals())

	def post(self,request):
		print("rijgiojg0re")
		try:
			name = request.POST.get("name")
			geography = request.POST.get("geography")
			srlevel = request.POST.get("srlevel")
			period = request.POST.get("period")
			functions = request.POST.get("functions")
			experience=request.POST.get("experience")
			day = request.POST.get("day")
			rate = request.POST.get("rate")
			user=request.POST.get('users')
			print("ahcsdjhsdafdfmndskjfnd"+str(user))
			automation = Automations(
				user_id=user,
				name=name,
				day=day,
				rate=rate
				)
			if geography=="0":
				automation.geography_status=False
			else:	
				automation.geography_id=geography
				automation.geography_status=True

			if srlevel=="0":
				automation.srlevel_status=False
			else:	
				automation.srlevel_id=srlevel
				automation.srlevel__status=True

			if functions=="0":
				automation.functionsatcompanyl_status=False
			else:	
				automation.functionsatcompany_id=functions
				automation.functionsatcompanyl_status=True

			if experience=="0":
				automation.yearsofexperience_status=False
			else:	
				automation.yearsofexperience_id=experience
				automation.yearsofexperience_status=True

			if period=="0":
				automation.period_status=False
			else:	
				automation.period_id=period
				automation.period_status=True
			automation.status=True
			automation.save()
			value=''
			if rate == 'W':
				value=7
			if rate == 'M':
				value=30
			save_cron=Cron(automation_id=automation.id,execution_rate=value)
			save_cron.save()
			messages.success(request, 'Automation added successfully')
		except Exception as e:
			raise e
		return HttpResponseRedirect(reverse('add'))

class ShowAutomations(TemplateView):
	template_name='index-three.html'
	def get(self,request):
		return render(request,self.template_name, locals())


class AllData(TemplateView):
	template_name='all.html'
	def get(self,request):
		scraped_data = AutomationData.objects.filter(status="P")
		return render(request,self.template_name, locals())

class ChangeAllStatus(View):

	def post(self,request):

		response = {}
		status =  request.POST.get('status')

		try:
			AutomationData.objects.all().update(status = status)	
			response["status"] = True
			response["msg"] = "Status is changed successfully."

		except Exception as e:
			response["status"] = True
			response["msg"] = "Some error occur. Please try again." + str(e)

		return HttpResponse(json.dumps(response), content_type="application/json")

class Actions(View):

	def post(self,request):
		response = {}
		ids =  request.POST.get('ids')
		id_list = ids.split(',')
		action =  request.POST.get('action')

		scraped_data = AutomationData.objects.filter(pk__in=id_list)

		if action == 'delete':
			scraped_data.delete()

		elif action == 'accept':
			scraped_data.update(status="A")

		elif action == 'reject':
			scraped_data.update(status="R")

		return HttpResponseRedirect('/alldata')


class Reject(TemplateView):
	template_name='reject.html'
	def get(self,request):
		scraped_data = AutomationData.objects.filter(status="R")
		return render(request,self.template_name, locals())

class Linked(TemplateView):
	template_name='linked.html'
	def get(self,request):
		return render(request,self.template_name, locals())

	def post(self, request):
		email=request.POST.get("email")
		pwd=request.POST.get ("password")

		try:
			check_email=LinkedIn.objects.get(email=email)

			messages.error(request,'This email already exists.')
			return render(request, self.template_name,locals())
			# return HttpResponseRedirect("linked")

		except LinkedIn.DoesNotExist as e:
			LinkedIn.objects.create(email=email,password=pwd)
			return HttpResponseRedirect("/linked/")

class Changestatus(View):
	def post(self,request):
		response = {}
		try:
			data_id = request.POST.get('id')
			status = request.POST.get('status')
			auto = AutomationData.objects.get(id=data_id)
			auto.status=status
			auto.save()

			response["status"] = True
			response["msg"] = "Status is changed successfully."
		except Exception as e:
			response["status"] = True
			response["msg"] = "Some error occur. Please try again."
		return HttpResponse(json.dumps(response), content_type="application/json")
			



class Database(TemplateView):
	template_name='database.html'
	def get(self,request):
		scraped_data = AutomationData.objects.filter(status="A")
		return render(request,self.template_name, locals())

class User(TemplateView):
	template_name='users.html'
	def get(self,request):
		user = LinkedIn.objects.all()
		print(user)
		return render(request,self.template_name, locals())

class DeleteUser(View):

scrap/templates/add_automation.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

      <!-- /.row -->
      <div class="row">
        <div class="col-xs-12">
          <div class="box box-main-section">
            <div class="messages">
              {% if messages %}
                  {% for message in messages %}
                  <p>{{ message }}</p>
                  {% endfor %}
              {% endif %}
            </div>
          <div class="box-header box-main-header-sub-content">
              <h3 class="box-title">Add automations</h3>
          </div>
      
           <form class="box-main-section-form-input-section" action="{% url 'add' %}" method="post">
            {% csrf_token %}
            <div class="combine-group-section">
            <label class="name">NAME</label>
            <input type="text" name="name" value="" placeholder="" required>
          </div>
            <div class="combine-group-section">
            <label class="Emails">User</label>
               <select name="users">
                  {% for users in user %}
                      <option value="{{ users.id }}">{{ users.email }}</option>
                  {% endfor %}
             </select>
            </div>
          <div class="combine-group-section">
            <label class="name">Geography</label>
            <select name="geography">
              <option value="0">Don't Apply</option>
              {% for location in locations %}
              <option value="{{ location.id }}">{{ location.title|title }}</option>
              {% endfor %}
            </select>
              </div>
                   <div class="combine-group-section">
            <label class="name">Seniority level</label>
            <select name="srlevel">
              <option value="0">Don't Apply</option>
              {% for level in srlevel %}
              <option value="{{ level.id }}">{{ level.title|upper }}</option>
              {% endfor %}
            </select>
              </div>

     <div class="combine-group-section">
            <label class="name">Years at company</label>
            <select name="period">
              <option value="0">Don't Apply</option>
              {% for time in period %}
              <option value="{{ time.id }}">{{ time.title|title }}</option>
              {% endfor %}
            </select>
              </div>

              <div class="combine-group-section">
                <label class="name">Years of Experience</label>
                <select name="experience">
                  <option value="0">Don't Apply</option>
                  {% for time in year_of_experience %}
                  <option value="{{ time.id }}">{{ time.title|title }}</option>
                  {% endfor %}
                </select>
              </div>
              <div class="combine-group-section">
            <label class="name">function</label>
            <select name="functions">
              <option value="0">Don't Apply</option>
              {% for function in functionatcom %}
              <option value="{{ function.id }}">{{ function.title|title }}</option>
              {% endfor %}
            </select>
              </div>


              <div class="combine-group-section-main-two">
            <label class="name">frequency day</label>
            <div class="combine-group-section-main-three">
            <h3>Day</h3>
            <select name="day">
              {% for choice in day_form.days_choices.field.choices %}
                    <option value="{{ choice.0 }}">{{ choice.1 }}</option>
              {% endfor %}
            </select>
          </div>
              <div class="combine-group-section-main-three four">
                <h3>Rate</h3>
            <select name="rate">
              {% for choice in rate_form.rate_choices.field.choices %}
                    <option value="{{ choice.0 }}">{{ choice.1 }}</option>
              {% endfor %}
            </select>
              </div>
            </div>
           


         

          <div class="combine-group-section-submit-btn">
            <input type="submit" value="save">
          </div>
          </div>
               </div>
           </div>

{% endblock %}

scrap/templates/all.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

      <!-- /.row -->
      <div class="row">
        <div class="col-xs-12">
          <div class="box box-main-section-approved">
          <div class="box-header box-main-header-sub-content-approved">
              <a href="#">All scraped data</a>

              <button type="button" class="btn btn-primary changestatus" value="P"> Pending All</button>
              <button type="button" class="btn btn-success changestatus" value="A"> Approve  All</button>
              <button type="button" class="btn btn-danger changestatus" value="R"> Reject All</button>
              </div>
      
              <div class="box-body box-main-body">

            <form class="form-horizontal" method="post" action="{% url 'actions' %}" id="actionForm">

              <div class="box-body">
                <div class="form-group">
                  <label for="inputEmail3" class="col-sm-2 control-label">Action</label>
                  {% csrf_token %}
                  <div class="col-sm-8">
                    <select class="form-control" name="action" id="action">
                      <option value="" disabled selected>Choose Action</option>
                      <option value="delete"> Delete Selected</option>
                      <option value="accept"> Accept Selected</option>
                      <option value="reject"> Reject Selected</option>
                    </select>
                    <input type="hidden" name="ids">
                  </div>
                   <button type="submit" class="btn btn-info  col-sm-1 ">Sign in</button>
                   <div class="col-sm-1"></div>

                </div>
              </div>
            </form>


              <table id="example_all_scraped" class="table table-bordered table-hover approved-database">
               
                <thead>
                
             <tr>
              <th>Select</th>
               <th>ID</th>
                  <th>COMPANY NAME</th>
                  <th>NAME</th>
                  <th>SENIORITY LEVEL</th>
                  <th>FUNCTION</th>
                 <th>DEGREE</th>
                 <th>GRAD. YEAR START</th>
                 <th>GRAD. YEAR END</th>
                 <th>URL</th>
                 <th>NTRY DATE</th>
                 <th>AUTOMATION NAME</th>
                 <th>DUPLICATE</th>
                 <th class='notexport'>STATUS</th>
                </tr>
                </thead>
                <tbody>
                  {% for datas in scraped_data %}
                <tr>
                  <td><input type="checkbox" value="{{datas.id}}" onclick="addval($(this))"></td>
                  <td> {{forloop.counter }} </td>
                 <td>{{ datas.companyname }}</td>
                  <td>{{ datas.name }}</td>
                  <td>{{ datas.senioritylevel }}</td>
                  <td>{{ datas.function }}</td>
                  <td>{{ datas.degree }}</td>
                  <td>{{ datas.gradyearstart }}</td>
                   <td>{{ datas.gradyearend }}</td>
                   <td><a href="{{ datas.url }}" target="_blank">Go to profile</a></td>
                   <td>{{ datas.automation.created_at }}</td>
                    <td>{{ datas.automation.name }}</td>
                    <td>
                       {% if datas.isduplicated %}
                        Yes
                      {% else %}
                        No
                      {% endif %}
                     </td>
                    <td>
                      <input type="radio" class="status" name="status{{forloop.counter }}" checked value="P" data-id="{{ datas.id }}">Pending<br>
                      <input type="radio" class="status" name="status{{forloop.counter }}" value="A" data-id="{{ datas.id }}">Approve<br>
                      <input type="radio" class="status" name="status{{forloop.counter }}" value="R" data-id="{{ datas.id }}">Reject<br>
                    </td>
                </tr>
                {% endfor %}

              
                
                </tbody>
              </table>




            </div>
            <!-- /.box-body -->


          </div>
        </div>



          </div>
<script type="text/javascript">
  var token = "{{ csrf_token }}";

  var ids = []
  function addval(value) {
    if (value.is(":checked")){
      ids.push(value.val());
    }
    else{
      var remove_Item = value.val();
      ids.splice($.inArray(remove_Item, ids),1);
    }
  }

</script>

  <!-- /.content-wrapper -->
{% endblock %}

scrap/templates/footer.html
{% load static %}
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
     
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="#">DASHBOARD</a>.</strong> All rights
    reserved.
  </footer>
</div>

scrap/templates/header.html
 {% load static %}
 <header class="main-header">
    <!-- Logo -->
    <a href="index2.html" class="logo">
      <span class="logo-mini"><b>DASHBOARD</b></span>
      <span class="logo-lg"><b>DASHBOARD</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <li>
            <a href="#" class="btn btn-flat">Sign out</a>
          </li>
        </ul>
      </div>
    </nav>
  </header>

scrap/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


      <!-- /.row -->
      <div class="row">
        <div class="col-xs-12">
          <div class="box box-main-section">
            <div class="box-header box-main-header">
              <h3 class="box-title">AUTOMATIONS</h3>
              <div class="box-title-button">
                <a href="{% url 'add' %}">Add automations</a>
              </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body box-main-body">
              <table id="example1" class="table table-bordered table-hover">
               
                <thead>
                
             <tr>
               <th>Automation Name</th>
                  <th>Geography</th>
                  <th>Seniority level</th>
                  <th>Year at company</th>
                  <th>Year of Experience</th>
                  <th>function</th>
                  <th>instance</th>
                  <th>schedule</th>
                  <th>Pause</th>
                  <th>Edit</th>
                  <th>Delete</th>
                </tr>
                </thead>
                <tbody>
                  {% for automation in automations %}
                  <tr>
                    <td>{{ automation.name }}({{ automation.get_rate_display }})</td>
                     <td>
                      {% if automation.geography_status %}
                        {{ automation.geography.title }}
                     {% else %}
                      Not selected
                     {% endif %}
                     </td>
                    <td>
                    {% if automation.srlevel_status %}
                      {{ automation.srlevel.title }}
                    {% else %}
                      Not selected
                     {% endif %}
                   </td>
                    <td>
                      {% if automation.period_status %}

                      {{ automation.period.title }}
                      {% else %}
                      Not selected
                     {% endif %}
                    </td>
                    <td>
                      {% if automation.yearsofexperience_status %}

                      {{ automation.yearsofexperience.title }}
                      {% else %}
                      Not selected
                     {% endif %}
                    </td>
                    <td>
                      {% if automation.functionsatcompanyl_status %}
                        

                      {{ automation.functionsatcompany.title }}
                      {% else %}
                      Not selected
                     {% endif %}
                    </td>
                    <td><a class="play" href="javascript:void(0)" id="{{automation.id}}">Play</a></td>
                     <td><a class="schedule" href="javascript:void(0)" id="{{automation.id}}">Play</a></td>  
                    
                      <input type="hidden" name="" class="linkedin-user" value="{{automation.user_id}}">
                     <td><a class="pause" href="javascript:void(0)" id="{{automation.id}}">Pause</a></td>
                      <td><a class="edit" data-id="" href="{% url 'edit_automation' automation.id  %}">Edit</a></td>
                       <td><a class="delete" href="javascript:void(0)"  data-id="{{automation.id}}">delete</a></td>
                  </tr>

                {% endfor %}
                </tbody>
              </table>
              </div>
              




            </div>
            <!-- /.box-body -->
          </div>
        </div>
        <!-- /.col -->
   
  <!-- /.content-wrapper -->
{% endblock %}  

{% block script %}
<script type="text/javascript">
  $('.schedule').click(function(){
  var id = $(this).attr('id');
  alert("Automation is scheduled.");
  $.ajax({
      url: 'add-cron',
      method: 'GET',
      data: {'automation_id':id},
      success: function(data) 
      {
        console.log("success");
      }

      });
});
$('.pause').click(function(){
  var id = $(this).attr('id');
  alert(id);
  $.ajax({
      url: 'pause',
      method: 'GET',
      data: {'automation_id':id},
      success: function(data) 
      {
        if(data.status==true){
          alert('Automation is stoped successfully.')
        }
        else{
          console.log("error");
        }
        
      }

      });
});
</script>
{% endblock %}